#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
# # Check Prettier standards

# echo '🏗️👷 Styling and Formatting your project before committing'

# # Format with Prettier standards
# npm run prettier-fix

# # Style with ESLint standards
# npm run lint-fix


#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Validating code styling and formatting before committing.'

# Check Prettier formatting
npm run prettier-check || (npm run git-reset-changes && (echo '🤢 Prettier Check Failed. 🤢'; false;))

# Check ESLint styling
npm run lint-check || (npm run git-reset-changes && (echo '🤢 ESLint Check Failed. 🤢'; false;))

# Everything OK
echo '✅ Committing your changes. ✅'